### ISSUE TITLE
Je kan een herkansing op dezelfde dag maken als je je achteraf uitschrijft.

### ISSUE THREAD

**Issue by Jelleas** [apltools/test-planner#3]
Een slimme en iets te eerlijke student heeft zich uit geschreven voor het net gemaakte toetsje om zich vervolgens weer in te schrijven voor dezelfde middag! ;)

**Comment by MarijnDoeve** [comment]
Tot wanneer mag een student zich uitschrijven? Tot het moment dat de toets begint?

**Comment by MarijnDoeve** [comment]
fixed in 4baecd3ec27d85f617791e81b4cd4b1d59708653
